version: "2"

services:
  ror:
    image: myrails
    ports:
      - "3000:3000"
    volumes:
      - ./src:/usr/src/app

  postgres:
    image: postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

volumes:
  src:
  data:
